const PROJECTS_DATA = [
  {
    id: 1,
    title: "TEAnimo",
    title_en: "TEAnimo",
    category: "ML/DL",
    description: "Aplicación de tamizaje para TEA con formulario clínico, generación de informe y resultados de evaluación asistidos por ML.",
    description_en: "TEA screening platform with clinical forms, report generation, and ML-assisted evaluation results.",
    longDescription: `TEAnimo es una plataforma de evaluación de riesgo TEA con arquitectura desacoplada Frontend + Backend, orientada a digitalizar el tamizaje inicial de forma clara y trazable.\n\nEl frontend está construido con React y Tailwind CSS, e incorpora cuestionarios clínicos, paneles visuales y generación de reportes PDF. El backend está implementado con FastAPI, procesa la evaluación con modelos de Machine Learning y almacena resultados en PostgreSQL.\n\nLa solución está concebida como apoyo al cribado temprano y no como diagnóstico definitivo, priorizando usabilidad, estructura clínica y continuidad técnica para despliegue en entornos reales.`,
    longDescription_en: `TEAnimo is a TEA risk-screening platform built with a decoupled Frontend + Backend architecture to digitalize early screening in a clear and traceable way.\n\nThe frontend is developed with React and Tailwind CSS, including clinical questionnaires, visual dashboards, and PDF report generation. The backend is built with FastAPI, processes evaluations with machine learning models, and stores results in PostgreSQL.\n\nThe solution is intended as early screening support rather than a definitive diagnosis tool, prioritizing usability, clinical structure, and technical continuity for real-world deployment.`,
    tags: ["React", "Tailwind CSS", "FastAPI", "PostgreSQL", "Pandas", "Joblib"],
    demo: "https://page.teanimo.tech/",
    github: "https://github.com/TEAnimo/Frontend.git",
    githubBackend: "https://github.com/TEAnimo/Backend.git",
    status: "Open Source",
    year: "2025",
    highlights: ["Frontend React + Tailwind para evaluación clínica", "Backend FastAPI con predicción ML", "Persistencia de resultados en PostgreSQL", "Exportación de reporte PDF y visualización de métricas"],
    highlights_en: ["React + Tailwind frontend for clinical evaluation", "FastAPI backend with ML prediction", "PostgreSQL result persistence", "PDF report export and metric visualization"],
    images: [
      "assets/proyectos/teanimo principal.png",
      "assets/proyectos/teanimo formulario de evaluacion.png",
      "assets/proyectos/teanimo resultado de evaluacion.png",
      "assets/proyectos/teanimo informe de evaluacion.png",
    ],
  },
  {
    id: 2,
    title: "Predicción de Autismo por Fusión de Embeddings",
    title_en: "Autism Prediction via Embedding Fusion",
    category: "ML/DL",
    description: "Aplicación de predicción de autismo mediante fusión de embeddings y evaluación supervisada para apoyar decisiones de tamizaje temprano.",
    description_en: "Autism risk prediction app using embedding fusion and supervised evaluation to support early screening decisions.",
    longDescription: `Este proyecto implementa una estrategia de fusión de embeddings para combinar representaciones de información relevante en una tarea de predicción de riesgo de autismo.\n\nLa aplicación permite ejecutar inferencia sobre nuevos registros y visualizar la salida de predicción de forma directa, facilitando el uso en contextos de exploración clínica y prototipado de modelos.\n\nEl enfoque prioriza una arquitectura reproducible, con separación entre preprocesamiento, representación vectorial y etapa de predicción, de modo que el pipeline pueda evolucionar con nuevas fuentes de datos o mejores embeddings en iteraciones futuras.`,
    longDescription_en: `This project implements an embedding-fusion strategy to combine relevant data representations for autism risk prediction.\n\nThe app allows inference on new records and presents prediction outputs clearly, making it practical for clinical exploration and model prototyping scenarios.\n\nThe approach emphasizes a reproducible architecture, separating preprocessing, vector representation, and prediction stages so the pipeline can evolve with new data sources and stronger embeddings.`,
    tags: ["Python", "PyTorch", "FastAPI", "Streamlit", "PostgreSQL", "Kubernetes"],
    demo: "https://app-prediccion-autismo-fusion-embeddings.streamlit.app/",
    github: "https://github.com/ErnestoSCL/app_prediccion_autismo_fusion_embeddings",
    status: "Open Source",
    year: "2025",
    highlights: ["Fusión de embeddings para predicción", "Interfaz de inferencia práctica", "Pipeline modular y reproducible", "Orientado a tamizaje temprano"],
    highlights_en: ["Embedding fusion for prediction", "Practical inference interface", "Modular and reproducible pipeline", "Focused on early screening"],
    images: [
      "assets/proyectos/app_prediccion_autismo_fusion_embeddings principal.png",
      "assets/proyectos/app_prediccion_autismo_fusion_embeddings prediction.png",
    ],
  },
  {
    id: 3,
    title: "Clasificación de Cáncer Bucal",
    title_en: "Oral Cancer Classification",
    category: "CV",
    description: "Modelo de clasificación para apoyo al tamizaje de cáncer bucal con medición de rendimiento y flujo de inferencia reproducible.",
    description_en: "Classification model for oral cancer screening support with performance tracking and a reproducible inference flow.",
    longDescription: `Proyecto de visión computacional orientado a la clasificación de imágenes para apoyar procesos de tamizaje de cáncer bucal.\n\nIncluye una etapa de entrenamiento supervisado y evaluación de desempeño, con especial énfasis en métricas de clasificación útiles para contexto clínico.\n\nLa implementación busca un balance entre rendimiento del modelo, trazabilidad de experimentos y facilidad para reutilizar el flujo en nuevas versiones del dataset.`,
    longDescription_en: `Computer vision project focused on image classification to support oral cancer screening workflows.\n\nIt includes supervised training and model performance evaluation with a strong focus on clinically relevant classification metrics.\n\nThe implementation balances model performance, experiment traceability, and easy reuse of the pipeline for future dataset versions.`,
    tags: ["Python", "PyTorch", "Flask", "Streamlit", "Docker", "PostgreSQL"],
    demo: "https://clasificacion-cancer-bucal.streamlit.app/",
    github: "https://github.com/ErnestoSCL/clasificacion-cancer-bucal",
    status: "Open Source",
    year: "2025",
    highlights: ["Clasificación aplicada a salud digital", "Evaluación de rendimiento del modelo", "Pipeline reproducible", "Enfoque en apoyo a tamizaje"],
    highlights_en: ["Classification applied to digital health", "Model performance evaluation", "Reproducible pipeline", "Screening-support focus"],
    images: [
      "assets/proyectos/clasificacion-cancer-bucal principal.png",
      "assets/proyectos/clasificacion-cancer-bucal rendimiento modelo.png",
    ],
  },
  {
    id: 4,
    title: "Asistente de Tamizaje de Leucemia",
    title_en: "Leukemia Screening Assistant",
    category: "ML/DL",
    description: "Asistente de apoyo al tamizaje de leucemia con monitoreo de experimentos, selección de mejor modelo y panel de métricas.",
    description_en: "Leukemia screening assistant with experiment tracking, best-model selection, and a performance dashboard.",
    longDescription: `Asistente orientado al análisis de datos para tamizaje de leucemia, con foco en el ciclo completo de entrenamiento, evaluación y seguimiento de modelos.\n\nSe incorpora trazabilidad experimental mediante MLflow para registrar ejecuciones, comparar variantes y conservar evidencia de desempeño durante la iteración.\n\nEl resultado es un flujo más ordenado para identificar el mejor modelo, revisar sus métricas y mantener una base sólida para mejoras futuras o despliegues controlados.`,
    longDescription_en: `Data-driven assistant for leukemia screening, focused on the full lifecycle of training, evaluation, and model monitoring.\n\nIt uses MLflow for experiment traceability, enabling run tracking, variant comparison, and performance evidence across iterations.\n\nThe result is a more structured workflow to identify the best model, review metrics, and maintain a strong base for future improvements or controlled deployment.`,
    tags: ["Python", "PyTorch", "Flask", "Streamlit", "MLflow", "PostgreSQL"],
    demo: "https://asistente-tamizaje-leucemia.streamlit.app/",
    github: "https://github.com/ErnestoSCL/asistente-tamizaje-leucemia",
    status: "Open Source",
    year: "2025",
    highlights: ["Seguimiento de experimentos con MLflow", "Comparación de modelos", "Panel de métricas del mejor modelo", "Enfoque en trazabilidad"],
    highlights_en: ["MLflow experiment tracking", "Model comparison", "Best-model metrics dashboard", "Traceability-focused workflow"],
    images: [
      "assets/proyectos/asistente-tamizaje-leucemia principal.png",
      "assets/proyectos/asistente-tamizaje-leucemia metricas mejor modelo.png",
      "assets/proyectos/asistente-tamizaje-leucemia mlfow historial mejor modelo.png",
    ],
  },
  {
    id: 5,
    title: "Predicción OSCC",
    title_en: "OSCC Prediction",
    category: "CV",
    description: "Aplicación para predicción de carcinoma oral de células escamosas (OSCC) con análisis de rendimiento y visualización de resultados.",
    description_en: "OSCC prediction app with performance analysis and result visualization.",
    longDescription: `Proyecto de apoyo a la predicción de OSCC (Oral Squamous Cell Carcinoma) a partir de imágenes, enfocado en combinar clasificación automática con revisión de rendimiento del modelo.\n\nLa aplicación organiza la inferencia y presenta resultados de manera clara, permitiendo revisar tanto salidas individuales como desempeño agregado.\n\nEl enfoque está diseñado para facilitar iteración experimental, documentar avances y mantener un flujo replicable de evaluación en un problema de salud digital.`,
    longDescription_en: `Project focused on OSCC (Oral Squamous Cell Carcinoma) prediction from images, combining automatic classification with model performance review.\n\nThe app structures inference and presents outputs clearly, making it easy to inspect both individual predictions and aggregate performance.\n\nThe workflow is designed to support experimentation, document progress, and keep evaluation reproducible for a digital health use case.`,
    tags: ["Python", "PyTorch", "FastAPI", "Streamlit", "Docker", "PostgreSQL"],
    demo: "https://app-prediccion-oscc-v1.streamlit.app/",
    github: "https://github.com/ErnestoSCL/app-prediccion-oscc",
    status: "Open Source",
    year: "2025",
    highlights: ["Predicción orientada a OSCC", "Visualización de rendimiento", "Flujo de inferencia reutilizable", "Aplicación enfocada en salud"],
    highlights_en: ["OSCC-focused prediction", "Performance visualization", "Reusable inference workflow", "Healthcare-oriented application"],
    images: [
      "assets/proyectos/app-prediccion-oscc principal.png",
      "assets/proyectos/app-prediccion-oscc Rendimiento modelo.png",
    ],
  },
  {
    id: 6,
    title: "PneumoVision-AI",
    title_en: "PneumoVision-AI",
    category: "CV",
    description: "Proyecto de visión computacional para detección asistida en imágenes médicas pulmonares con enfoque en interpretación clínica.",
    description_en: "Computer vision project for assisted detection in lung medical images with a clinical-interpretation focus.",
    longDescription: `PneumoVision-AI explora la aplicación de técnicas de visión computacional en imágenes pulmonares para apoyar procesos de detección asistida.\n\nEl proyecto se centra en la preparación del flujo de análisis, entrenamiento y validación, manteniendo una estructura clara para poder iterar con nuevos datos y mejoras de arquitectura.\n\nSu aporte principal es servir como base técnica para experimentación en IA aplicada a imágenes médicas, con foco en trazabilidad y potencial de transferencia a escenarios reales.`,
    longDescription_en: `PneumoVision-AI explores computer vision techniques on lung images to support assisted detection workflows.\n\nThe project focuses on analysis, training, and validation flow setup, keeping a clear structure for iteration with new data and architecture improvements.\n\nIts core value is providing a technical base for experimentation in AI for medical imaging, with strong attention to traceability and transferability to real scenarios.`,
    tags: ["Python", "TensorFlow", "Keras", "Gradio", "NumPy", "Pillow"],
    demo: "https://huggingface.co/spaces/ErnestoRepos/neumonia_prediction",
    github: "https://github.com/ErnestoSCL/PneumoVision-AI",
    status: "Open Source",
    year: "2025",
    highlights: ["Enfoque en imágenes pulmonares", "Pipeline para iteración experimental", "Base para evolución de modelos", "Orientado a IA en salud"],
    highlights_en: ["Lung-imaging focus", "Pipeline for iterative experimentation", "Foundation for model evolution", "Healthcare AI orientation"],
    images: [
      "assets/proyectos/PneumoVision-AI principal.png",
    ],
  },
  {
    id: 7,
    title: "DentalVision EDA",
    title_en: "DentalVision EDA",
    category: "Data Eng",
    description: "Análisis exploratorio de datos para imágenes odontológicas: calidad, distribución, propiedades y revisión visual de dataset.",
    description_en: "Exploratory data analysis for dental images: quality, distribution, image properties, and visual dataset inspection.",
    longDescription: `DentalVision EDA es un proyecto de análisis exploratorio sobre un conjunto de imágenes odontológicas, enfocado en comprender la calidad de datos antes del modelado.\n\nIncluye revisión de distribución de clases, análisis de propiedades de imagen y exploración visual mediante galerías para detectar sesgos o inconsistencias tempranas.\n\nEste trabajo aporta una base robusta para decisiones de preprocesamiento y entrenamiento, reduciendo riesgos de experimentación sobre datos poco caracterizados.`,
    longDescription_en: `DentalVision EDA is an exploratory analysis project over a dental image dataset, focused on understanding data quality before modeling.\n\nIt includes class-distribution review, image-property analysis, and visual gallery exploration to identify early bias or data inconsistencies.\n\nThis work provides a robust foundation for preprocessing and training decisions, reducing experimentation risk on poorly characterized data.`,
    tags: ["Python", "Streamlit", "Plotly", "Pandas", "NumPy", "SciPy"],
    demo: "https://dentalvision-eda.streamlit.app/",
    github: "https://github.com/ErnestoSCL/dentalvision-eda",
    status: "Open Source",
    year: "2025",
    highlights: ["Análisis de calidad de datos", "Distribución de imágenes y clases", "Exploración de propiedades visuales", "Base para pipeline de modelado"],
    highlights_en: ["Data quality analysis", "Image and class distribution review", "Visual property exploration", "Foundation for modeling pipeline"],
    images: [
      "assets/proyectos/dentalvision-eda principal.png",
      "assets/proyectos/dentalvision-eda calidad de datos.png",
      "assets/proyectos/dentalvision-eda distribucion de imagenes.png",
      "assets/proyectos/dentalvision-eda galeria de img.png",
      "assets/proyectos/dentalvision-eda propiedad de imagen.png",
    ],
  },
  {
    id: 8,
    title: "Asistente Médico RAG",
    title_en: "MedQuAD RAG Medical Assistant",
    category: "GenAI",
    description: "Chatbot médico con arquitectura RAG sobre el corpus MedQuAD del NIH, con memoria conversacional, guardrails de seguridad y citación de fuentes.",
    description_en: "Medical chatbot with a RAG architecture over the NIH's MedQuAD corpus, featuring conversation memory, safety guardrails, and source citations.",
    longDescription: `Asistente Médico RAG es un chatbot conversacional que responde preguntas médicas en español fundamentando cada respuesta en el corpus MedQuAD de los Institutos Nacionales de Salud (NIH) de Estados Unidos, en vez de depender del conocimiento general del modelo.\n\nEl backend está construido con FastAPI y LangChain, con búsqueda semántica sobre más de 38,000 fragmentos indexados en Supabase/pgvector (embeddings de OpenAI, similitud coseno con reranking por LLM). Las preguntas en español se traducen automáticamente al inglés para la recuperación, ya que el corpus está en ese idioma, y la memoria conversacional permite dar seguimiento a las últimas interacciones de cada usuario.\n\nEl sistema incorpora guardrails de seguridad tanto en la entrada (detección de inyección de prompts y contenido tóxico) como en la salida (disclaimers clínicos obligatorios), y cada respuesta cita explícitamente el documento fuente del que proviene, priorizando la trazabilidad sobre una conversación fluida sin respaldo.`,
    longDescription_en: `Asistente Médico RAG is a conversational chatbot that answers medical questions in Spanish, grounding every response in the MedQuAD corpus from the U.S. National Institutes of Health (NIH) instead of relying on the model's general knowledge.\n\nThe backend is built with FastAPI and LangChain, with semantic search over more than 38,000 indexed chunks in Supabase/pgvector (OpenAI embeddings, cosine similarity with LLM-based reranking). Spanish questions are automatically translated to English for retrieval, since the corpus itself is in English, and conversational memory lets the assistant follow up on each user's most recent interactions.\n\nThe system includes safety guardrails on both input (prompt-injection and toxicity detection) and output (mandatory clinical disclaimers), and every answer explicitly cites the source document it came from, prioritizing traceability over unsupported conversational fluency.`,
    tags: ["Python", "FastAPI", "LangChain", "OpenAI", "Supabase", "Docker"],
    github: "https://github.com/ErnestoSCL/medquad-rag-api",
    status: "Open Source",
    year: "2026",
    highlights: ["RAG con Supabase/pgvector y reranking por LLM", "Guardrails de seguridad en entrada y salida", "Memoria conversacional por usuario", "Citación de fuentes en cada respuesta"],
    highlights_en: ["RAG with Supabase/pgvector and LLM-based reranking", "Input and output safety guardrails", "Per-user conversational memory", "Source citation on every response"],
    images: [
      "assets/proyectos/asistente-medico-rag principal.png",
      "assets/proyectos/asistente-medico-rag conversacion.png",
    ],
  },
  {
    id: 9,
    title: "Generador de Exámenes Médicos",
    title_en: "Medical Exam Generator",
    category: "GenAI",
    description: "Generador de exámenes médicos de opción múltiple mediante fine-tuning LoRA de un modelo de lenguaje, con inferencia 100% local y citación de fuente por pregunta.",
    description_en: "Multiple-choice medical exam generator using LoRA fine-tuning of a language model, with 100% local inference and per-question source citation.",
    longDescription: `Generador de Exámenes Médicos crea simulacros de examen de opción múltiple en español a partir del corpus MedQuAD del NIH, permitiendo elegir tema, cantidad de preguntas y activar auto-verificación antes de rendir el examen.\n\nEl núcleo del proyecto es un modelo Qwen3 de 4B parámetros ajustado con LoRA sobre más de 2,400 temas médicos, ejecutado completamente en local (sin llamadas a APIs externas ni costo por consulta). La generación alcanza una calidad de salida equivalente a GPT-4o-mini en pruebas estadísticas, usando una fracción de los tokens que requeriría un enfoque few-shot.\n\nCada pregunta muestra el documento del NIH del que proviene junto a un link de verificación, y un mecanismo de auto-verificación ejecuta el modelo base sin el adaptador LoRA para detectar defectos antes de mostrar la pregunta al usuario. Un hallazgo interesante de este proceso fue descubrir que el adaptador a veces regenera contenido en vez de validarlo, evidenciando los límites del fine-tuning especializado.`,
    longDescription_en: `Generador de Exámenes Médicos creates multiple-choice practice exams in Spanish from the NIH's MedQuAD corpus, letting the user pick a topic, question count, and enable auto-verification before taking the exam.\n\nThe core of the project is a 4B-parameter Qwen3 model fine-tuned with LoRA on more than 2,400 medical topics, running entirely locally (no external API calls or per-query cost). Output quality matches GPT-4o-mini in statistical testing, using a fraction of the tokens a few-shot approach would require.\n\nEach question displays the NIH document it came from along with a verification link, and a self-verification mechanism runs the base model without the LoRA adapter to catch defects before showing a question to the user. An interesting finding from this process was discovering that the adapter sometimes regenerates content instead of truly validating it, exposing the limits of narrow fine-tuning.`,
    tags: ["Python", "PyTorch", "Qwen3", "LoRA", "Streamlit", "Hugging Face"],
    github: "https://github.com/ErnestoSCL/generador-examenes-medicos",
    status: "Open Source",
    year: "2026",
    highlights: ["Fine-tuning LoRA sobre Qwen3-4B", "Inferencia 100% local, sin costo por consulta", "Auto-verificación con el modelo base", "Fuente NIH citada en cada pregunta"],
    highlights_en: ["LoRA fine-tuning on Qwen3-4B", "100% local inference, no per-query cost", "Self-verification against the base model", "NIH source cited on every question"],
    images: [
      "assets/proyectos/generador-examenes-medicos principal.jpeg",
      "assets/proyectos/generador-examenes-medicos pregunta.jpeg",
      "assets/proyectos/generador-examenes-medicos revision.jpeg",
      "assets/proyectos/generador-examenes-medicos resultado.jpeg",
    ],
  },
  {
    id: 10,
    title: "SynapseOps Platform",
    title_en: "SynapseOps Platform",
    category: "ML/DL",
    description: "Plataforma MLOps low-code para entrenar, versionar, desplegar y monitorear modelos de visión computacional sin escribir código de infraestructura.",
    description_en: "Low-code MLOps platform to train, version, deploy, and monitor computer vision models without writing infrastructure code.",
    longDescription: `SynapseOps es una plataforma MLOps containerizada pensada para entornos de laboratorio, que permite gestionar el ciclo de vida completo de un modelo —desde la ingesta de datos hasta el despliegue y monitoreo— desde una interfaz web, sin necesidad de conocimientos de infraestructura.\n\nEl frontend está construido en React con TypeScript, con un canvas low-code de arrastrar y soltar (React Flow) para diseñar pipelines. El backend combina un orquestador en Spring Boot (WebFlux) con un motor de ML en FastAPI, coordinados mediante Apache Kafka; los experimentos se registran en MLflow y los modelos entrenados se despliegan automáticamente como servicios FastAPI independientes en Docker.\n\nColaboré en este proyecto como QA Tester, validando flujos end-to-end de la plataforma —desde la carga de datasets hasta el despliegue y monitoreo de modelos— y reportando defectos sobre el pipeline low-code y el stack de observabilidad (Prometheus, Grafana, detección de drift con Evidently AI).`,
    longDescription_en: `SynapseOps is a containerized MLOps platform built for lab environments, managing the full model lifecycle — from data ingestion to deployment and monitoring — through a browser interface, with no infrastructure knowledge required.\n\nThe frontend is built with React and TypeScript, with a drag-and-drop low-code canvas (React Flow) for designing pipelines. The backend combines a Spring Boot (WebFlux) orchestrator with a FastAPI ML engine, coordinated through Apache Kafka; experiments are tracked in MLflow, and trained models are automatically deployed as independent FastAPI services in Docker.\n\nI collaborated on this project as a QA Tester, validating end-to-end platform flows — from dataset upload through model deployment and monitoring — and reporting defects across the low-code pipeline and the observability stack (Prometheus, Grafana, drift detection with Evidently AI).`,
    tags: ["React", "TypeScript", "Spring Boot", "FastAPI", "Kafka", "Docker"],
    github: "https://github.com/Synapse-Ops/SynapseOps-platform",
    status: "Open Source",
    year: "2026",
    highlights: ["Canvas low-code para pipelines de ML", "Despliegue automático como servicios Docker", "Stack de observabilidad con Prometheus y Grafana", "QA end-to-end sobre el pipeline completo"],
    highlights_en: ["Low-code canvas for ML pipelines", "Automatic deployment as Docker services", "Observability stack with Prometheus and Grafana", "End-to-end QA across the full pipeline"],
    images: [
      "assets/proyectos/synapseops-platform principal.png",
    ],
  },
];
