const PROJECTS_DATA = [
  {
    id: 1,
    title: "TEAnimo",
    category: "ML/DL",
    description: "Aplicación de tamizaje para TEA con formulario clínico, generación de informe y resultados de evaluación asistidos por ML.",
    description_en: "TEA screening platform with clinical forms, report generation, and ML-assisted evaluation results.",
    longDescription: `TEAnimo es una plataforma de evaluación de riesgo TEA con arquitectura desacoplada Frontend + Backend, orientada a digitalizar el tamizaje inicial de forma clara y trazable.\n\nEl frontend está construido con React y Tailwind CSS, e incorpora cuestionarios clínicos, paneles visuales y generación de reportes PDF. El backend está implementado con FastAPI, procesa la evaluación con modelos de Machine Learning y almacena resultados en PostgreSQL.\n\nLa solución está concebida como apoyo al cribado temprano y no como diagnóstico definitivo, priorizando usabilidad, estructura clínica y continuidad técnica para despliegue en entornos reales.`,
    longDescription_en: `TEAnimo is a TEA risk-screening platform built with a decoupled Frontend + Backend architecture to digitalize early screening in a clear and traceable way.\n\nThe frontend is developed with React and Tailwind CSS, including clinical questionnaires, visual dashboards, and PDF report generation. The backend is built with FastAPI, processes evaluations with machine learning models, and stores results in PostgreSQL.\n\nThe solution is intended as early screening support rather than a definitive diagnosis tool, prioritizing usability, clinical structure, and technical continuity for real-world deployment.`,
    tags: ["React", "Tailwind CSS", "FastAPI", "PostgreSQL", "Pandas", "Joblib"],
    demo: "https://page.teanimo.tech/",
    github: "https://github.com/TEAnimo/Frontend.git",
    githubBackend: "https://github.com/TEAnimo/Backend.git",
    status: "Open Source",
    year: "2025",
    highlights: ["Frontend React + Tailwind para evaluación clínica", "Backend FastAPI con predicción ML", "Persistencia de resultados en PostgreSQL", "Exportación de reporte PDF y visualización de métricas"],
    highlights_en: ["React + Tailwind frontend for clinical evaluation", "FastAPI backend with ML prediction", "PostgreSQL result persistence", "PDF report export and metric visualization"],
    images: [
      "assets/proyectos/teanimo principal.png",
      "assets/proyectos/teanimo formulario de evaluacion.png",
      "assets/proyectos/teanimo resultado de evaluacion.png",
      "assets/proyectos/teanimo informe de evaluacion.png",
    ],
  },
  {
    id: 2,
    title: "Predicción de Autismo por Fusión de Embeddings",
    category: "ML/DL",
    description: "Aplicación de predicción de autismo mediante fusión de embeddings y evaluación supervisada para apoyar decisiones de tamizaje temprano.",
    description_en: "Autism risk prediction app using embedding fusion and supervised evaluation to support early screening decisions.",
    longDescription: `Este proyecto implementa una estrategia de fusión de embeddings para combinar representaciones de información relevante en una tarea de predicción de riesgo de autismo.\n\nLa aplicación permite ejecutar inferencia sobre nuevos registros y visualizar la salida de predicción de forma directa, facilitando el uso en contextos de exploración clínica y prototipado de modelos.\n\nEl enfoque prioriza una arquitectura reproducible, con separación entre preprocesamiento, representación vectorial y etapa de predicción, de modo que el pipeline pueda evolucionar con nuevas fuentes de datos o mejores embeddings en iteraciones futuras.`,
    longDescription_en: `This project implements an embedding-fusion strategy to combine relevant data representations for autism risk prediction.\n\nThe app allows inference on new records and presents prediction outputs clearly, making it practical for clinical exploration and model prototyping scenarios.\n\nThe approach emphasizes a reproducible architecture, separating preprocessing, vector representation, and prediction stages so the pipeline can evolve with new data sources and stronger embeddings.`,
    tags: ["Python", "PyTorch", "FastAPI", "Streamlit", "PostgreSQL", "Kubernetes"],
    demo: "https://app-prediccion-autismo-fusion-embeddings.streamlit.app/",
    github: "https://github.com/ErnestoSCL/app_prediccion_autismo_fusion_embeddings",
    status: "Open Source",
    year: "2025",
    highlights: ["Fusión de embeddings para predicción", "Interfaz de inferencia práctica", "Pipeline modular y reproducible", "Orientado a tamizaje temprano"],
    highlights_en: ["Embedding fusion for prediction", "Practical inference interface", "Modular and reproducible pipeline", "Focused on early screening"],
    images: [
      "assets/proyectos/app_prediccion_autismo_fusion_embeddings principal.png",
      "assets/proyectos/app_prediccion_autismo_fusion_embeddings prediction.png",
    ],
  },
  {
    id: 3,
    title: "Clasificación de Cáncer Bucal",
    category: "CV",
    description: "Modelo de clasificación para apoyo al tamizaje de cáncer bucal con medición de rendimiento y flujo de inferencia reproducible.",
    description_en: "Classification model for oral cancer screening support with performance tracking and a reproducible inference flow.",
    longDescription: `Proyecto de visión computacional orientado a la clasificación de imágenes para apoyar procesos de tamizaje de cáncer bucal.\n\nIncluye una etapa de entrenamiento supervisado y evaluación de desempeño, con especial énfasis en métricas de clasificación útiles para contexto clínico.\n\nLa implementación busca un balance entre rendimiento del modelo, trazabilidad de experimentos y facilidad para reutilizar el flujo en nuevas versiones del dataset.`,
    longDescription_en: `Computer vision project focused on image classification to support oral cancer screening workflows.\n\nIt includes supervised training and model performance evaluation with a strong focus on clinically relevant classification metrics.\n\nThe implementation balances model performance, experiment traceability, and easy reuse of the pipeline for future dataset versions.`,
    tags: ["Python", "PyTorch", "Flask", "Streamlit", "Docker", "PostgreSQL"],
    demo: "https://clasificacion-cancer-bucal.streamlit.app/",
    github: "https://github.com/ErnestoSCL/clasificacion-cancer-bucal",
    status: "Open Source",
    year: "2025",
    highlights: ["Clasificación aplicada a salud digital", "Evaluación de rendimiento del modelo", "Pipeline reproducible", "Enfoque en apoyo a tamizaje"],
    highlights_en: ["Classification applied to digital health", "Model performance evaluation", "Reproducible pipeline", "Screening-support focus"],
    images: [
      "assets/proyectos/clasificacion-cancer-bucal principal.png",
      "assets/proyectos/clasificacion-cancer-bucal rendimiento modelo.png",
    ],
  },
  {
    id: 4,
    title: "Asistente de Tamizaje de Leucemia",
    category: "ML/DL",
    description: "Asistente de apoyo al tamizaje de leucemia con monitoreo de experimentos, selección de mejor modelo y panel de métricas.",
    description_en: "Leukemia screening assistant with experiment tracking, best-model selection, and a performance dashboard.",
    longDescription: `Asistente orientado al análisis de datos para tamizaje de leucemia, con foco en el ciclo completo de entrenamiento, evaluación y seguimiento de modelos.\n\nSe incorpora trazabilidad experimental mediante MLflow para registrar ejecuciones, comparar variantes y conservar evidencia de desempeño durante la iteración.\n\nEl resultado es un flujo más ordenado para identificar el mejor modelo, revisar sus métricas y mantener una base sólida para mejoras futuras o despliegues controlados.`,
    longDescription_en: `Data-driven assistant for leukemia screening, focused on the full lifecycle of training, evaluation, and model monitoring.\n\nIt uses MLflow for experiment traceability, enabling run tracking, variant comparison, and performance evidence across iterations.\n\nThe result is a more structured workflow to identify the best model, review metrics, and maintain a strong base for future improvements or controlled deployment.`,
    tags: ["Python", "PyTorch", "Flask", "Streamlit", "MLflow", "PostgreSQL"],
    demo: "https://asistente-tamizaje-leucemia.streamlit.app/",
    github: "https://github.com/ErnestoSCL/asistente-tamizaje-leucemia",
    status: "Open Source",
    year: "2025",
    highlights: ["Seguimiento de experimentos con MLflow", "Comparación de modelos", "Panel de métricas del mejor modelo", "Enfoque en trazabilidad"],
    highlights_en: ["MLflow experiment tracking", "Model comparison", "Best-model metrics dashboard", "Traceability-focused workflow"],
    images: [
      "assets/proyectos/asistente-tamizaje-leucemia principal.png",
      "assets/proyectos/asistente-tamizaje-leucemia metricas mejor modelo.png",
      "assets/proyectos/asistente-tamizaje-leucemia mlfow historial mejor modelo.png",
    ],
  },
  {
    id: 5,
    title: "Predicción OSCC",
    category: "CV",
    description: "Aplicación para predicción de carcinoma oral de células escamosas (OSCC) con análisis de rendimiento y visualización de resultados.",
    description_en: "OSCC prediction app with performance analysis and result visualization.",
    longDescription: `Proyecto de apoyo a la predicción de OSCC (Oral Squamous Cell Carcinoma) a partir de imágenes, enfocado en combinar clasificación automática con revisión de rendimiento del modelo.\n\nLa aplicación organiza la inferencia y presenta resultados de manera clara, permitiendo revisar tanto salidas individuales como desempeño agregado.\n\nEl enfoque está diseñado para facilitar iteración experimental, documentar avances y mantener un flujo replicable de evaluación en un problema de salud digital.`,
    longDescription_en: `Project focused on OSCC (Oral Squamous Cell Carcinoma) prediction from images, combining automatic classification with model performance review.\n\nThe app structures inference and presents outputs clearly, making it easy to inspect both individual predictions and aggregate performance.\n\nThe workflow is designed to support experimentation, document progress, and keep evaluation reproducible for a digital health use case.`,
    tags: ["Python", "PyTorch", "FastAPI", "Streamlit", "Docker", "PostgreSQL"],
    demo: "https://app-prediccion-oscc-v1.streamlit.app/",
    github: "https://github.com/ErnestoSCL/app-prediccion-oscc",
    status: "Open Source",
    year: "2025",
    highlights: ["Predicción orientada a OSCC", "Visualización de rendimiento", "Flujo de inferencia reutilizable", "Aplicación enfocada en salud"],
    highlights_en: ["OSCC-focused prediction", "Performance visualization", "Reusable inference workflow", "Healthcare-oriented application"],
    images: [
      "assets/proyectos/app-prediccion-oscc principal.png",
      "assets/proyectos/app-prediccion-oscc Rendimiento modelo.png",
    ],
  },
  {
    id: 6,
    title: "PneumoVision-AI",
    category: "CV",
    description: "Proyecto de visión computacional para detección asistida en imágenes médicas pulmonares con enfoque en interpretación clínica.",
    description_en: "Computer vision project for assisted detection in lung medical images with a clinical-interpretation focus.",
    longDescription: `PneumoVision-AI explora la aplicación de técnicas de visión computacional en imágenes pulmonares para apoyar procesos de detección asistida.\n\nEl proyecto se centra en la preparación del flujo de análisis, entrenamiento y validación, manteniendo una estructura clara para poder iterar con nuevos datos y mejoras de arquitectura.\n\nSu aporte principal es servir como base técnica para experimentación en IA aplicada a imágenes médicas, con foco en trazabilidad y potencial de transferencia a escenarios reales.`,
    longDescription_en: `PneumoVision-AI explores computer vision techniques on lung images to support assisted detection workflows.\n\nThe project focuses on analysis, training, and validation flow setup, keeping a clear structure for iteration with new data and architecture improvements.\n\nIts core value is providing a technical base for experimentation in AI for medical imaging, with strong attention to traceability and transferability to real scenarios.`,
    tags: ["Python", "TensorFlow", "Keras", "Gradio", "NumPy", "Pillow"],
    demo: "https://huggingface.co/spaces/ErnestoRepos/neumonia_prediction",
    github: "https://github.com/ErnestoSCL/PneumoVision-AI",
    status: "Open Source",
    year: "2025",
    highlights: ["Enfoque en imágenes pulmonares", "Pipeline para iteración experimental", "Base para evolución de modelos", "Orientado a IA en salud"],
    highlights_en: ["Lung-imaging focus", "Pipeline for iterative experimentation", "Foundation for model evolution", "Healthcare AI orientation"],
    images: [
      "assets/proyectos/PneumoVision-AI principal.png",
    ],
  },
  {
    id: 7,
    title: "DentalVision EDA",
    category: "Data Eng",
    description: "Análisis exploratorio de datos para imágenes odontológicas: calidad, distribución, propiedades y revisión visual de dataset.",
    description_en: "Exploratory data analysis for dental images: quality, distribution, image properties, and visual dataset inspection.",
    longDescription: `DentalVision EDA es un proyecto de análisis exploratorio sobre un conjunto de imágenes odontológicas, enfocado en comprender la calidad de datos antes del modelado.\n\nIncluye revisión de distribución de clases, análisis de propiedades de imagen y exploración visual mediante galerías para detectar sesgos o inconsistencias tempranas.\n\nEste trabajo aporta una base robusta para decisiones de preprocesamiento y entrenamiento, reduciendo riesgos de experimentación sobre datos poco caracterizados.`,
    longDescription_en: `DentalVision EDA is an exploratory analysis project over a dental image dataset, focused on understanding data quality before modeling.\n\nIt includes class-distribution review, image-property analysis, and visual gallery exploration to identify early bias or data inconsistencies.\n\nThis work provides a robust foundation for preprocessing and training decisions, reducing experimentation risk on poorly characterized data.`,
    tags: ["Python", "Streamlit", "Plotly", "Pandas", "NumPy", "SciPy"],
    demo: "https://dentalvision-eda.streamlit.app/",
    github: "https://github.com/ErnestoSCL/dentalvision-eda",
    status: "Open Source",
    year: "2025",
    highlights: ["Análisis de calidad de datos", "Distribución de imágenes y clases", "Exploración de propiedades visuales", "Base para pipeline de modelado"],
    highlights_en: ["Data quality analysis", "Image and class distribution review", "Visual property exploration", "Foundation for modeling pipeline"],
    images: [
      "assets/proyectos/dentalvision-eda principal.png",
      "assets/proyectos/dentalvision-eda calidad de datos.png",
      "assets/proyectos/dentalvision-eda distribucion de imagenes.png",
      "assets/proyectos/dentalvision-eda galeria de img.png",
      "assets/proyectos/dentalvision-eda propiedad de imagen.png",
    ],
  },
];
