const PROJECTS_DATA = [
  {
    id: 1,
    title: "TEAnimo",
    category: "ML/DL",
    description: "Aplicación de tamizaje para TEA con formulario clínico, generación de informe y resultados de evaluación asistidos por ML.",
    longDescription: `TEAnimo es una plataforma de evaluación de riesgo TEA con arquitectura desacoplada Frontend + Backend, orientada a digitalizar el tamizaje inicial de forma clara y trazable.\n\nEl frontend está construido con React y Tailwind CSS, e incorpora cuestionarios clínicos, paneles visuales y generación de reportes PDF. El backend está implementado con FastAPI, procesa la evaluación con modelos de Machine Learning y almacena resultados en PostgreSQL.\n\nLa solución está concebida como apoyo al cribado temprano y no como diagnóstico definitivo, priorizando usabilidad, estructura clínica y continuidad técnica para despliegue en entornos reales.`,
    tags: ["React", "Tailwind CSS", "FastAPI", "PostgreSQL", "Pandas", "Joblib"],
    demo: "https://page.teanimo.tech/",
    github: "https://github.com/TEAnimo/Frontend.git",
    githubBackend: "https://github.com/TEAnimo/Backend.git",
    status: "Open Source",
    year: "2025",
    highlights: ["Frontend React + Tailwind para evaluación clínica", "Backend FastAPI con predicción ML", "Persistencia de resultados en PostgreSQL", "Exportación de reporte PDF y visualización de métricas"],
    images: [
      "assets/proyectos/teanimo principal.png",
      "assets/proyectos/teanimo formulario de evaluacion.png",
      "assets/proyectos/teanimo resultado de evaluacion.png",
      "assets/proyectos/teanimo informe de evaluacion.png",
    ],
  },
  {
    id: 2,
    title: "Predicción de Autismo por Fusión de Embeddings",
    category: "ML/DL",
    description: "Aplicación de predicción de autismo mediante fusión de embeddings y evaluación supervisada para apoyar decisiones de tamizaje temprano.",
    longDescription: `Este proyecto implementa una estrategia de fusión de embeddings para combinar representaciones de información relevante en una tarea de predicción de riesgo de autismo.\n\nLa aplicación permite ejecutar inferencia sobre nuevos registros y visualizar la salida de predicción de forma directa, facilitando el uso en contextos de exploración clínica y prototipado de modelos.\n\nEl enfoque prioriza una arquitectura reproducible, con separación entre preprocesamiento, representación vectorial y etapa de predicción, de modo que el pipeline pueda evolucionar con nuevas fuentes de datos o mejores embeddings en iteraciones futuras.`,
    tags: ["Python", "PyTorch", "FastAPI", "Streamlit", "PostgreSQL", "Kubernetes"],
    demo: "https://app-prediccion-autismo-fusion-embeddings.streamlit.app/",
    github: "https://github.com/ErnestoSCL/app_prediccion_autismo_fusion_embeddings",
    status: "Open Source",
    year: "2025",
    highlights: ["Fusión de embeddings para predicción", "Interfaz de inferencia práctica", "Pipeline modular y reproducible", "Orientado a tamizaje temprano"],
    images: [
      "assets/proyectos/app_prediccion_autismo_fusion_embeddings principal.png",
      "assets/proyectos/app_prediccion_autismo_fusion_embeddings prediction.png",
    ],
  },
  {
    id: 3,
    title: "Clasificación de Cáncer Bucal",
    category: "CV",
    description: "Modelo de clasificación para apoyo al tamizaje de cáncer bucal con medición de rendimiento y flujo de inferencia reproducible.",
    longDescription: `Proyecto de visión computacional orientado a la clasificación de imágenes para apoyar procesos de tamizaje de cáncer bucal.\n\nIncluye una etapa de entrenamiento supervisado y evaluación de desempeño, con especial énfasis en métricas de clasificación útiles para contexto clínico.\n\nLa implementación busca un balance entre rendimiento del modelo, trazabilidad de experimentos y facilidad para reutilizar el flujo en nuevas versiones del dataset.`,
    tags: ["Python", "PyTorch", "Flask", "Streamlit", "Docker", "PostgreSQL"],
    demo: "https://clasificacion-cancer-bucal.streamlit.app/",
    github: "https://github.com/ErnestoSCL/clasificacion-cancer-bucal",
    status: "Open Source",
    year: "2025",
    highlights: ["Clasificación aplicada a salud digital", "Evaluación de rendimiento del modelo", "Pipeline reproducible", "Enfoque en apoyo a tamizaje"],
    images: [
      "assets/proyectos/clasificacion-cancer-bucal principal.png",
      "assets/proyectos/clasificacion-cancer-bucal rendimiento modelo.png",
    ],
  },
  {
    id: 4,
    title: "Asistente de Tamizaje de Leucemia",
    category: "ML/DL",
    description: "Asistente de apoyo al tamizaje de leucemia con monitoreo de experimentos, selección de mejor modelo y panel de métricas.",
    longDescription: `Asistente orientado al análisis de datos para tamizaje de leucemia, con foco en el ciclo completo de entrenamiento, evaluación y seguimiento de modelos.\n\nSe incorpora trazabilidad experimental mediante MLflow para registrar ejecuciones, comparar variantes y conservar evidencia de desempeño durante la iteración.\n\nEl resultado es un flujo más ordenado para identificar el mejor modelo, revisar sus métricas y mantener una base sólida para mejoras futuras o despliegues controlados.`,
    tags: ["Python", "PyTorch", "Flask", "Streamlit", "MLflow", "PostgreSQL"],
    demo: "https://asistente-tamizaje-leucemia.streamlit.app/",
    github: "https://github.com/ErnestoSCL/asistente-tamizaje-leucemia",
    status: "Open Source",
    year: "2025",
    highlights: ["Seguimiento de experimentos con MLflow", "Comparación de modelos", "Panel de métricas del mejor modelo", "Enfoque en trazabilidad"],
    images: [
      "assets/proyectos/asistente-tamizaje-leucemia principal.png",
      "assets/proyectos/asistente-tamizaje-leucemia metricas mejor modelo.png",
      "assets/proyectos/asistente-tamizaje-leucemia mlfow historial mejor modelo.png",
    ],
  },
  {
    id: 5,
    title: "Predicción OSCC",
    category: "CV",
    description: "Aplicación para predicción de carcinoma oral de células escamosas (OSCC) con análisis de rendimiento y visualización de resultados.",
    longDescription: `Proyecto de apoyo a la predicción de OSCC (Oral Squamous Cell Carcinoma) a partir de imágenes, enfocado en combinar clasificación automática con revisión de rendimiento del modelo.\n\nLa aplicación organiza la inferencia y presenta resultados de manera clara, permitiendo revisar tanto salidas individuales como desempeño agregado.\n\nEl enfoque está diseñado para facilitar iteración experimental, documentar avances y mantener un flujo replicable de evaluación en un problema de salud digital.`,
    tags: ["Python", "PyTorch", "FastAPI", "Streamlit", "Docker", "PostgreSQL"],
    demo: "https://app-prediccion-oscc-v1.streamlit.app/",
    github: "https://github.com/ErnestoSCL/app-prediccion-oscc",
    status: "Open Source",
    year: "2025",
    highlights: ["Predicción orientada a OSCC", "Visualización de rendimiento", "Flujo de inferencia reutilizable", "Aplicación enfocada en salud"],
    images: [
      "assets/proyectos/app-prediccion-oscc principal.png",
      "assets/proyectos/app-prediccion-oscc Rendimiento modelo.png",
    ],
  },
  {
    id: 6,
    title: "PneumoVision-AI",
    category: "CV",
    description: "Proyecto de visión computacional para detección asistida en imágenes médicas pulmonares con enfoque en interpretación clínica.",
    longDescription: `PneumoVision-AI explora la aplicación de técnicas de visión computacional en imágenes pulmonares para apoyar procesos de detección asistida.\n\nEl proyecto se centra en la preparación del flujo de análisis, entrenamiento y validación, manteniendo una estructura clara para poder iterar con nuevos datos y mejoras de arquitectura.\n\nSu aporte principal es servir como base técnica para experimentación en IA aplicada a imágenes médicas, con foco en trazabilidad y potencial de transferencia a escenarios reales.`,
    tags: ["Python", "TensorFlow", "Keras", "Gradio", "NumPy", "Pillow"],
    demo: "https://huggingface.co/spaces/ErnestoRepos/neumonia_prediction",
    github: "https://github.com/ErnestoSCL/PneumoVision-AI",
    status: "Open Source",
    year: "2025",
    highlights: ["Enfoque en imágenes pulmonares", "Pipeline para iteración experimental", "Base para evolución de modelos", "Orientado a IA en salud"],
    images: [
      "assets/proyectos/PneumoVision-AI principal.png",
    ],
  },
  {
    id: 7,
    title: "DentalVision EDA",
    category: "Data Eng",
    description: "Análisis exploratorio de datos para imágenes odontológicas: calidad, distribución, propiedades y revisión visual de dataset.",
    longDescription: `DentalVision EDA es un proyecto de análisis exploratorio sobre un conjunto de imágenes odontológicas, enfocado en comprender la calidad de datos antes del modelado.\n\nIncluye revisión de distribución de clases, análisis de propiedades de imagen y exploración visual mediante galerías para detectar sesgos o inconsistencias tempranas.\n\nEste trabajo aporta una base robusta para decisiones de preprocesamiento y entrenamiento, reduciendo riesgos de experimentación sobre datos poco caracterizados.`,
    tags: ["Python", "Streamlit", "Plotly", "Pandas", "NumPy", "SciPy"],
    demo: "https://dentalvision-eda.streamlit.app/",
    github: "https://github.com/ErnestoSCL/dentalvision-eda",
    status: "Open Source",
    year: "2025",
    highlights: ["Análisis de calidad de datos", "Distribución de imágenes y clases", "Exploración de propiedades visuales", "Base para pipeline de modelado"],
    images: [
      "assets/proyectos/dentalvision-eda principal.png",
      "assets/proyectos/dentalvision-eda calidad de datos.png",
      "assets/proyectos/dentalvision-eda distribucion de imagenes.png",
      "assets/proyectos/dentalvision-eda galeria de img.png",
      "assets/proyectos/dentalvision-eda propiedad de imagen.png",
    ],
  },
];
